sudo: required
services: 
  - docker

before_install:
  - docker build -t docker-app -f Dockerfile.dev .

script:
  - docker run docker-app npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: 'docker-app'
  env: 'DockerApp-env'
  bucket_name: 'elasticbeanstalk-us-west-2-585426387297'
  bucket_path: 'docker'
  on
    branch: 'master'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY